### ISSUE TITLE
Draft up a problem statement/specification/block diagram initial draft for our benchside meeting

### ISSUE THREAD

**Issue by ToddHuaJi** [ToddHuaJi/FlappyDrone#17]
Combine #14 #12 #13 into one sheet of paper, double-sided.

This can start once all three issues are reviewed and closed.

**Comment by ToddHuaJi** [comment]
- [ ] #14  

- [x] #12  

- [x] #13

**Comment by ToddHuaJi** [comment]
All blocking issues were closed. This issue is unblocked

**Comment by ToddHuaJi** [comment]
Here is the link for our first daft: [https://docs.google.com/document/d/10ubwM2a-3D57OoUZ7GkltBiqKIZPfpf0nDRbTAOUK24/edit](url)

Take a look and let me know if there is anything you would like to change.

**Comment by kaiqiann** [comment]
I am ok with the draft

**Comment by ToddHuaJi** [comment]
After today's meeting with Wally. I think we need to rework our problem statement and system spec.

- [ ] I will add the humidity part to it. 

- [ ] We probably need a better block diagram as well.

**Comment by ToddHuaJi** [comment]
Closing this issue, because it is reviewed and due tomorrow
