### ISSUE TITLE
coordinate a first meeting with Mr. Sayed

### ISSUE THREAD

**Issue by ConleyGao** [ToddHuaJi/FlappyDrone#20]
He's available  8a-8p. (774) 217-1866
-When do we want to make a call, 
-List of question ?
-who want to contact Sayed, or  a group called with everyone around just in case of new question pop up?? 
-plan for a day to meet him in UMass

**Comment by ConleyGao** [comment]
I can call him maybe tomorrow but I need answers for these questions

**Comment by ToddHuaJi** [comment]
I suggest you text him first. 
Aske him does he want to call us individually or a group call. I would suggest noting heavy first

**Comment by ConleyGao** [comment]
Texted, waiting for response

**Comment by ConleyGao** [comment]
group meeting is preferred , we need to setup a time

**Comment by ToddHuaJi** [comment]
Let's talk about this in today's meeting. We should have enough time.

**Comment by ConleyGao** [comment]
please generate a list of questions You would like to ask . 
1. what parts would be sponsored by them 
2. when would we start getting parts , such as drone kit controller 
3. who is our consultant, do we reach him ?? 
4. is there more specific requirements, 
5. any restriction on open source code

**Comment by ToddHuaJi** [comment]
I have another question:

Is there any special restriction on how much weight we can mount on the drone? Are we free to mount whatever we need with the weight capacity of the drone?

I am asking this because we might need to use a motor to rotate the depth vision camera, which might add a lot of weight.

**Comment by ToddHuaJi** [comment]
I have more questions, so I am going to make a list of what we have 

1. what parts would be sponsored by them
2. when would we start getting parts, such as drone kit controller
3. who is our consultant, do we reach him ??
4. is there more specific requirements,
5. any restriction on open source code
6. Is there any special restriction on how much weight we can mount on the drone? Are we free to mount whatever we need with the weight capacity of the drone?
7. What kind of obstacle we are talking about here? A surface like a wall? What's the smallest obstacle we need to worry about?

**Comment by ToddHuaJi** [comment]
1.ask them to come to our review
2. do they want weekly report?

**Comment by ToddHuaJi** [comment]
Did that
