### ISSUE TITLE
research on power supply

### ISSUE THREAD

**Issue by kaiqiann** [ToddHuaJi/FlappyDrone#26]

**Comment by kaiqiann** [comment]
https://www.horizonhobby.com/pdf/EFL-LiPoSafetyWarnings.pdf
As Mr. Sayed have talked about the safety issues of using and charging Lipo Batteries. This is safety guide related to that issue.

**Comment by tony5598** [comment]
We will come back to this issue should we run into any problems with power distribution or creating a custom PCB for power distribution
