### ISSUE TITLE
Research Drone Spec sheet

### ISSUE THREAD

**Issue by kaiqiann** [ToddHuaJi/FlappyDrone#27]
- read through and get a general idea

**Comment by ToddHuaJi** [comment]
I am taking this. I have done some reading on this already, so I have a good start

**Comment by ToddHuaJi** [comment]
Nothing we didn't expect. It also came with different size of propeller pair, which can be helpful. 
It has its own speed controller frimware which will save us some work.

Any question from you guys? @kaiqiann @ConleyGao @tony5598

**Comment by ToddHuaJi** [comment]
Closing, no question asked.
