### ISSUE TITLE
hardware system plan

### ISSUE THREAD

**Issue by ConleyGao** [ToddHuaJi/FlappyDrone#33]
Consider the hardware system constraints.

- [x] What we need to pay attention to during development.
- [x] Positioning of our sensors

**Comment by ToddHuaJi** [comment]
Things we need to pay attention to on the hardware side.
1. If we can avoid moving part, then avoid it. Sir Newton said something very interesting about every action and equal reaction. 
2. Our system should stand high humidity and low light environment. That means no exposed or close wires.
3. Power consumption is not a HUGE problem, but it is a problem. Sensors should take as less power as possible.
4. Weight management can be a problem if we are not careful.

**Comment by ToddHuaJi** [comment]
The full doc can be view here: https://docs.google.com/document/d/1WyB2ONcInvhH3Myy-slTSmuRxXq3B11NduXFPHUl6yQ/edit?usp=sharing
