### ISSUE TITLE
sensor research

### ISSUE THREAD

**Issue by ConleyGao** [ToddHuaJi/FlappyDrone#34]
List all the possible sensors you can find:
- What's the range? Both how far and how wide.
- How accurate the sensors can be?
- Power consumption?
- Any hardware accelerator in place to speed up?
- How fault tolerant it can be?
- Anything else you think would be important

**Comment by kaiqiann** [comment]
[Sensors research.docx](https://github.com/ToddHuaJi/FlappyDrone/files/2430130/Sensors.research.docx)

I have added one or two sensors in each different categories. let me know if you guys need more information

**Comment by ToddHuaJi** [comment]
**Can you upload this to our google drive? I need to make notes and comments there.**

FYI, that stereoscopic camera software is PC only. I would say find a few more stereoscopic cameras because that might be the main detection sensor. The other ones look okay though.

**Comment by ConleyGao** [comment]
http://ardupilot.org/copter/docs/common-lightware-sf40c-objectavoidance.html#common-lightware-sf40c-objectavoidance

http://ardupilot.org/copter/docs/common-teraranger-tower-objectavoidance.html#common-teraranger-tower-objectavoidance

Could you take a look at these two sensors , are they suitable for this project ?? power consumption ... things like that  so we can decide which one is better.
Also, for the sensors you found , do they use MAVLink protocols ?

**Comment by ToddHuaJi** [comment]
> http://ardupilot.org/copter/docs/common-lightware-sf40c-objectavoidance.html#common-lightware-sf40c-objectavoidance
> 
> http://ardupilot.org/copter/docs/common-teraranger-tower-objectavoidance.html#common-teraranger-tower-objectavoidance
> 
> Could you take a look at these two sensors , are they suitable for this project ?? power consumption ... things like that so we can decide which one is better.
> Also, for the sensors you found , do they use MAVLink protocols ?

The first one cost $999, [https://lightware.co.za/products/sf40-c-100-m](url) If one motor is 10W, which is unlikely, then without considering the Pi, we have 40+20 = 60 W. This will drain our battery pretty fast.
The sensor itself will spin, and that can be a pain for our gyrometer. We need to compensate the counter spin from drone, and this will drain the battery even more! 

The second one is $699, [https://www.robotshop.com/en/terabee-teraranger-tower-evo-600hz-8-sensors-tof-rangefinder.html?gclid=Cj0KCQjw6MHdBRCtARIsAEigMxHE-s-IiIubSlqKmcy-Vp176OPiTDFzRt38yGI-p0tbW3DFeAIxuoQaAkjAEALw_wcB](url). The power consumption is less, and it looks very easy to mount. The only thing I am worried about this thing is the **accuracy**. **±12cm** is quite awful for our close range detection. You can miss almost 5 inches with this thing.
