### ISSUE TITLE
Bluetooth beacon 

### ISSUE THREAD

**Issue by ToddHuaJi** [ToddHuaJi/FlappyDrone#35]
does it work for electromagnetic field

**Comment by ToddHuaJi** [comment]
According to my research, Bluetooth signal can travel 100 meters, but in our heavy interference environment, I don't believe that will be the same. There is no easy way to verify this, and we already have a design plan without this. 
Here is what I suggest we do. Lets put this as a "nice to have feature". If we can finish our prototype ahead of our schedule, then we can start exploring this kind of things. I think this blue tooth beacon will turn out to be a critical unknown in our project. 

**Marking this for review**

**Comment by tony5598** [comment]
Also bluetooth beacons will be hard to place in this environment, there are definitely areas that humans can't reach
