### ISSUE TITLE
[Emergency] -- Raspberry Pi 3 B+ PoE pins need to go

### ISSUE THREAD

**Issue by ToddHuaJi** [ToddHuaJi/FlappyDrone#40]
![image](https://user-images.githubusercontent.com/28654028/46585431-c794c900-ca3e-11e8-9270-18756f51183c.png)
The red circle pins are for PoE hat, a new feature of Raspberry. Only B+(what we have right now) have this feature. This will prevent us attaching the Pi with Navio.

This needs to be resolve ASAP!!!

**Comment by tony5598** [comment]
So these extra pins are on the Pi and not the NavIO right?

**Comment by ToddHuaJi** [comment]
> So these extra pins are on the Pi and not the NavIO right?

Correct, they are from the latest feature on the Pi (which is useless to us)

**Comment by ToddHuaJi** [comment]
Closing this issue. We cut the pin. 😈
