### ISSUE TITLE
Ordering One sensor for testing purpous

### ISSUE THREAD

**Issue by ToddHuaJi** [ToddHuaJi/FlappyDrone#41]
How do you guys feel about ordering one sensor this week so it will get here right after PDR. We can start looking at how hard it is to implement our own sensor drive(FrontEnd and BackEnd)

**Comment by ToddHuaJi** [comment]
I personally think there is no blocking issue on this. We should start messing with ArduPilot library soon.

**Comment by kaiqiann** [comment]
it's probably the thing we will do right after PDR. And yes. I suggest we could order the Plan A sensor, which costs 40 bucks for one.

**Comment by ToddHuaJi** [comment]
> it's probably the thing we will do right after PDR. And yes. I suggest we could order the Plan A sensor, which costs 40 bucks for one.

Can you fill out a bill of material for Mr.Sayed to order the purchase? There should be a template on the SDP desktop. Please bring this up in the meeting tomorrow.

**Comment by ToddHuaJi** [comment]
Closing this because we gave Wally the ordering sheet.
