### ISSUE TITLE
[MDR Deliverables] ---- Giving out warning signals when Detecting a surface

### ISSUE THREAD

**Issue by ToddHuaJi** [ToddHuaJi/FlappyDrone#57]
**Feel free to create sub-ticket for this task and link that ticket to his one**

Lead: Tony

Developing standalone Cpp code for the following:
- [x] Giving out **command line** warning when sensor reading(individual sensor) is below a certain number (Distance Limit)

- [x] Being able to read a **custom** int for Distance Limit from a different file (text?) 

- [x] [**Bonus for MDR**]  Having **two different Distance Limit**, warning and suspend fligh. The code is able to read them from a specific file.

- [ ] [**Bonus for MDR**] Being able to map the warning to a audio alarm on the RC control (Pilot control on the ground)

**Comment by ToddHuaJi** [comment]
Related issue: #25 #53

**Comment by ToddHuaJi** [comment]
Uploaded a feature that satisfies the first three item of this ticket.

Waiting for review. @kaiqiann @ConleyGao @tony5598

**Comment by kaiqiann** [comment]
MDR deliverable is done
