### ISSUE TITLE
PCB board (Schematic, PCB drawing, printing on chip)

### ISSUE THREAD

**Issue by tony5598** [ToddHuaJi/FlappyDrone#79]

**Comment by ConleyGao** [comment]
This is done, I'm comfortable paying out of pocket because idk how to reimburse this  . Whoever is comfortable may pay. Otherwise I will ask some people on Monday.

If you are concerned with pcb correctness, you may review it using the link under 
https://easyeda.com/hao.gao1996/mux-sdp

**Comment by ConleyGao** [comment]
not comfortable *  ,,  

to buy,   export gerber  zip file -> generate fabrication file

**Comment by ToddHuaJi** [comment]
Closing, moving to integration testing #81
